/*
*
@author tri.tran on 2/18/19
*
*/

export default {
    //on internet connection change (true/false)
    ON_INTERNET_CONNECTION_CHANGE: 'ON_INTERNET_CONNECTION_CHANGE',

    //do login
    DO_LOGIN: 'DO_LOGIN',
    DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',
    DO_LOGIN_FAILURE: 'DO_LOGIN_FAILURE',

    SHOW_NOTICED_DIALOG: 'SHOW_NOTICED_DIALOG',
    HIDE_NOTICED_DIALOG: 'HIDE_NOTICED_DIALOG',

    //do Logout
    DO_LOGOUT: 'DO_LOGOUT',
    DO_LOGOUT_SUCCESS: 'DO_LOGOUT_SUCCESS',
    DO_LOGOUT_FAILURE: 'DO_LOGOUT_FAILURE',

    //auto login
    SAVE_AUTO_LOGIN: 'SAVE_AUTO_LOGIN',
    SAVE_AUTO_LOGIN_SUCCESS: 'SAVE_AUTO_LOGIN_SUCCESS',
    SAVE_AUTO_LOGIN_FAILURE: 'SAVE_AUTO_LOGIN_FAILURE',

    GET_AUTO_LOGIN: 'GET_AUTO_LOGIN',
    GET_AUTO_LOGIN_SUCCESS: 'GET_AUTO_LOGIN_SUCCESS',
    GET_AUTO_LOGIN_FAILURE: 'GET_AUTO_LOGIN_FAILURE',

    //list appointments
    GET_APPOINTMENT: 'GET_APPOINTMENT',
    GET_APPOINTMENT_SUCCESS: 'GET_APPOINTMENT_SUCCESS',
    GET_APPOINTMENT_FAILURE: 'GET_APPOINTMENT_FAILURE',

    //list history appointments
    GET_HISTORY_APPOINTMENT: 'GET_HISTORY_APPOINTMENT',
    GET_HISTORY_APPOINTMENT_SUCCESS: 'GET_HISTORY_APPOINTMENT_SUCCESS',
    GET_HISTORY_APPOINTMENT_FAILURE: 'GET_HISTORY_APPOINTMENT_FAILURE',

    //staff
    UPDATE_STAFF: 'UPDATE_STAFF',
    UPDATE_STAFF_SUCCESS: 'UPDATE_STAFF_SUCCESS',
    UPDATE_STAFF_FAILURE: 'UPDATE_STAFF_FAILURE',

    //change password
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    //forgot password
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    //booking detail
    GET_BOOKING_DETAIL: 'GET_BOOKING_DETAIL',
    GET_BOOKING_DETAIL_SUCCESS: 'GET_BOOKING_DETAIL_SUCCESS',
    GET_BOOKING_DETAIL_FAILURE: 'GET_BOOKING_DETAIL_FAILURE',

    //change state of booking
    CHANGE_STATE_BOOKING: 'CHANGE_STATE_BOOKING',
    CHANGE_STATE_BOOKING_SUCCESS: 'CHANGE_STATE_BOOKING_SUCCESS',
    CHANGE_STATE_BOOKING_FAILURE: 'CHANGE_STATE_BOOKING_FAILURE',

    //list comments
    GET_COMMENTS: 'GET_COMMENTS',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

    //post comment
    POST_COMMENT: 'POST_COMMENT',
    POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
    POST_COMMENT_FAILURE: 'POST_COMMENT_FAILURE',

    //list history state changing of booking
    GET_HISTORY_STATE: 'GET_HISTORY_STATE',
    GET_HISTORY_STATE_SUCCESS: 'GET_HISTORY_STATE_SUCCESS',
    GET_HISTORY_STATE_FAILURE: 'GET_HISTORY_STATE_FAILURE',

    //update device token
    UPDATE_DEVICE_TOKEN: 'UPDATE_DEVICE_TOKEN',
    UPDATE_DEVICE_TOKEN_SUCCESS: 'UPDATE_DEVICE_TOKEN_SUCCESS',
    UPDATE_DEVICE_TOKEN_FAILURE: 'UPDATE_DEVICE_TOKEN_FAILURE',

    //read all notification
    READ_ALL_NOTIFICATION: 'READ_ALL_NOTIFICATION',
    READ_ALL_NOTIFICATION_SUCCESS: 'READ_ALL_NOTIFICATION_SUCCESS',
    READ_ALL_NOTIFICATION_FAILURE: 'READ_ALL_NOTIFICATION_FAILURE',

    //read all notification
    READ_NOTIFICATION: 'READ_NOTIFICATION',
    READ_NOTIFICATION_SUCCESS: 'READ_NOTIFICATION_SUCCESS',
    READ_NOTIFICATION_FAILURE: 'READ_NOTIFICATION_FAILURE',

    //GET NOTIFICATIONS
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',

    //CHANGE NOTIFICATIONS
    CHANGE_NOTIFICATION_UNREAD: 'CHANGE_NOTIFICATION_UNREAD',

    //Toast message
    TOAST_MESSAGE: 'TOAST_MESSAGE',

    //GET NOTIFICATIONS
    GET_APPOINTMENT_NOTI: 'GET_APPOINTMENT_NOTI',
    GET_APPOINTMENT_NOTI_SUCCESS: 'GET_APPOINTMENT_NOTI_SUCCESS',
    GET_APPOINTMENT_NOTI_FAILURE: 'GET_APPOINTMENT_NOTI_FAILURE',
}
