/*
*
@author tri.tran on 2/18/19
*
*/

export const ACTION_TYPE = {
    //on internet connection change (true/false)
    ON_INTERNET_CONNECTION_CHANGE: 'ON_INTERNET_CONNECTION_CHANGE',

    //get data information of mobile app
    DO_APP_DATA: 'DO_APP_DATA',
    DO_APP_DATA_SUCCESS: 'DO_APP_DATA_SUCCESS',
    DO_APP_DATA_FAILURE: 'DO_APP_DATA_FAILURE',

    //do login
    DO_LOGIN: 'DO_LOGIN',
    DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',
    DO_LOGIN_FAILURE: 'DO_LOGIN_FAILURE',

    SHOW_NOTICED_DIALOG: 'SHOW_NOTICED_DIALOG',
    HIDE_NOTICED_DIALOG: 'HIDE_NOTICED_DIALOG',

    //do Logout
    DO_LOGOUT: 'DO_LOGOUT',
    DO_LOGOUT_SUCCESS: 'DO_LOGOUT_SUCCESS',
    DO_LOGOUT_FAILURE: 'DO_LOGOUT_FAILURE',

    DO_AUTO_LOGIN: 'GET_AUTO_LOGIN',

    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
    GET_PRODUCT_CATEGORIES_SUCCESS: 'GET_PRODUCT_CATEGORIES_SUCCESS',
    GET_PRODUCT_CATEGORIES_FAILURE: 'GET_PRODUCT_CATEGORIES_FAILURE',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

    GET_SPECIAL_OFFER: 'GET_SPECIAL_OFFER',
    GET_SPECIAL_OFFER_SUCCESS: 'GET_SPECIAL_OFFER_SUCCESS',
    GET_SPECIAL_OFFER_FAILURE: 'GET_SPECIAL_OFFER_FAILURE',

    DO_LIKE_PRODUCT: 'DO_LIKE_PRODUCT',
    DO_LIKE_PRODUCT_SUCCESS: 'DO_LIKE_PRODUCT_SUCCESS',
    DO_LIKE_PRODUCT_FAILURE: 'DO_LIKE_PRODUCT_FAILURE',

    DO_SEARCH: 'DO_SEARCH',
    DO_SEARCH_SUCCESS: 'DO_SEARCH_SUCCESS',
    DO_SEARCH_FAILURE: 'DO_SEARCH_FAILURE',
}
